In [3]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [5]:
# !pip install -r requirements.txt

In [25]:
# !pip install -U langchain langchain-core langchain-community langchain-text-splitters sentence-transformers

In [28]:
# !pip install -U langchain-huggingface

In [29]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)

result = embeddings.embed_query("Hello world")
print(len(result))

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

768

In [6]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [7]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [8]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [9]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

In [31]:
from langchain_community.document_loaders import TextLoader

raw_documents = TextLoader(
    r"tagged_description.txt",
    encoding="utf-8"
).load()
# raw_documents = TextLoader(r"tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 373, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 482, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 211, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 513, which is longer than the specified 0
Created a chunk of size 752, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 728, which is longer than the specified 0
Created a chunk of size 721, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 473, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 681, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 553, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 787, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 533, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 563, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 410, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 595, which is longer than the specified 0
Created a chunk of size 476, which is longer than the specified 0
Created a chunk of size 459, which is longer than the specified 0
Created a chunk of size 257, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 614, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 887, which is longer than the specified 0
Created a chunk of size 693, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 479, which is longer than the specified 0
Created a chunk of size 300, which is longer than the specified 0
Created a chunk of size 520, which is longer than the specified 0
Created a chunk of size 647, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 686, which is longer than the specified 0
Created a chunk of size 548, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 406, which is longer than the specified 0
Created a chunk of size 1184, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 1057, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 417, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 526, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 899, which is longer than the specified 0
Created a chunk of size 1270, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 1635, which is longer than the specified 0
Created a chunk of size 436, which is longer than the specified 0
Created a chunk of size 249, which is longer than the specified 0
Created a chunk of size 777, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 514, which is longer than the specified 0
Created a chunk of size 958, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 851, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1119, which is longer than the specified 0
Created a chunk of size 836, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 235, which is longer than the specified 0
Created a chunk of size 732, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 773, which is longer than the specified 0
Created a chunk of size 278, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 445, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 912, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 844, which is longer than the specified 0
Created a chunk of size 1126, which is longer than the specified 0
Created a chunk of size 1073, which is longer than the specified 0
Created a chunk of size 1318, which is longer than the specified 0
Created a chunk of size 361, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 240, which is longer than the specified 0
Created a chunk of size 171, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1141, which is longer than the specified 0
Created a chunk of size 1004, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 954, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 639, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 793, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 254, which is longer than the specified 0
Created a chunk of size 1422, which is longer than the specified 0
Created a chunk of size 1083, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 806, which is longer than the specified 0
Created a chunk of size 1812, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1180, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 1642, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 1930, which is longer than the specified 0
Created a chunk of size 872, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 577, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1142, which is longer than the specified 0
Created a chunk of size 557, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 221, which is longer than the specified 0
Created a chunk of size 1135, which is longer than the specified 0
Created a chunk of size 722, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 765, which is longer than the specified 0
Created a chunk of size 606, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 857, which is longer than the specified 0
Created a chunk of size 1032, which is longer than the specified 0
Created a chunk of size 189, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 495, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 348, which is longer than the specified 0
Created a chunk of size 733, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 1015, which is longer than the specified 0
Created a chunk of size 970, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 544, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 207, which is longer than the specified 0
Created a chunk of size 376, which is longer than the specified 0
Created a chunk of size 931, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 854, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 324, which is longer than the specified 0
Created a chunk of size 241, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 704, which is longer than the specified 0
Created a chunk of size 1912, which is longer than the specified 0
Created a chunk of size 395, which is longer than the specified 0
Created a chunk of size 485, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 556, which is longer than the specified 0
Created a chunk of size 386, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 425, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 166, which is longer than the specified 0
Created a chunk of size 624, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 994, which is longer than the specified 0
Created a chunk of size 847, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 336, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2030, which is longer than the specified 0
Created a chunk of size 396, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 698, which is longer than the specified 0
Created a chunk of size 822, which is longer than the specified 0
Created a chunk of size 354, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 195, which is longer than the specified 0
Created a chunk of size 508, which is longer than the specified 0
Created a chunk of size 663, which is longer than the specified 0
Created a chunk of size 1282, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1056, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 269, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 225, which is longer than the specified 0
Created a chunk of size 222, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 969, which is longer than the specified 0
Created a chunk of size 613, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 289, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 963, which is longer than the specified 0
Created a chunk of size 232, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 786, which is longer than the specified 0
Created a chunk of size 648, which is longer than the specified 0
Created a chunk of size 984, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0

In [32]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [35]:
db_books = Chroma.from_documents(
    documents,
    embedding=embeddings)

In [36]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='75e9288a-e3e1-4b6b-be93-8174ee6c391f', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(id='40b25d37-3da3-4e8b-ab52-2a0a2c93c8e0', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='ac27b406-218f-4f36-a430-fceddabc5575', metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='9b44c934-bd35-46d3-9070-6b3859cdd8fd', metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='f70e90bd-656a-43e0-9c72-d46b083e7012', metadata={'source': 'tagged_description.txt'}, page_content='9780763620875 When Judy Moody gets serious about protecting the environment, her little brother Stink thinks she is overdoing it, but she manages to inspire her third grade class to undertake an award-winning, environment-saving project. Reprint.'),
 Document(id='24160dea-bd47-4fd9-95f0-a92d37ebda88', metadata={'source': 'tagged_description.txt'}, page_content="9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton's seriously silly signature animals."),
 Document(id='78dbbc14-c68a-4501-8854-88139695cd5e', metadata={'source': 'tagged_description.txt'}, page_content="9780312369347 Peter Rabbit, Mr. McGregor, and many other Beatrix Potter characters remain in the hearts of millions. However, though Potter is a household name around the world, few know the woman behind the illustrations. Her personal life, including a romantic relationship with her publisher, Norman Warne, and her significant achievements outside of children's literature remain largely unknown. In Linda Lear's enchanting new biography, we get the life story of this incredible, funny, and independent woman. As one of the first female naturalists in the world, Potter brought the beauty and importance of nature back into the imagination at a time when plunder was more popular than preservation. Through her art she sought to encourage conservation and change the world. With never before seen illustrations and intimate detail, Lear goes beyond our perrenial fascination with Potter as a writer and illustrator of children's books, and delves deeply into the life of a most unusual and gifted woman--one whose art was timeless, and whose generosity left an indelible imprint on the countryside."),
 Document(id='34571b8a-e938-4777-81f7-dee7423695ee', metadata={'source': 'tagged_description.txt'}, page_content="9780060959036 Barbara Kingsolver's fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel's intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."),
 Document(id='ef5accc1-b4f7-406b-a26f-1d750a85d792', metadata={'source': 'tagged_description.txt'}, page_content="9780064434874 Long ago, a little girl named Laura Ingalls lived in a little house in the Big Woods of Wisconsin with her Pa, her Ma, her sisters, Mary and Carrie, and their good old bulldog, Jack. Winter was just around the corner, and Laura worked hard to help make the little house ready for the cold days ahead. Soon there was frost on the windows and snow on the ground, but Laura and her folks were warm and cozy in their snug little house in the Big Woods. Laura Ingalls Wilder's Little House books have been cherished by generations of readers. Now for the first time, the youngest readers can share her adventures in these very special picture books adapted from Laura Ingalls Wilder's beloved storybooks. Renée Graef's warm paintings, inspired by Garth Williams' classic Little House illustrations, bring Laura and her family lovingly to life."),
 Document(id='c7632bda-fa32-4170-addb-29f3f263cf3e', metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects.")]

In [43]:
isbn = docs[0].page_content.split()[0].strip()

if isbn.isdigit():
    result = books[books["isbn13"] == int(isbn)]
else:
    print("Invalid ISBN format")


# books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

Invalid ISBN format

In [44]:
#semantic book recommendation engine function

def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [46]:
retrieve_semantic_recommendations("A book to teach 30 years boys about ethics")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
113,9780060507404,0060507403,The Cheese Monkeys,Chip Kidd,Fiction,http://books.google.com/books/content?id=wkCm2...,"After 15 years of designing more than 1,500 bo...",2002.0,3.75,288.0,4570.0,The Cheese Monkeys: A Novel in Two Semesters,9780060507404 After 15 years of designing more...
148,9780060564780,0060564784,The Kindness of Strangers,Katrina Kittle,Fiction,http://books.google.com/books/content?id=nDhTB...,"A young widow raising two boys, Sarah Laden is...",2007.0,4.01,400.0,11432.0,The Kindness of Strangers,"9780060564780 A young widow raising two boys, ..."
293,9780060927196,0060927194,Success Stories,Russell Banks,Fiction,http://books.google.com/books/content?id=bGIs7...,"In Sucess Stories, an exceptionally varied yet...",1996.0,3.72,192.0,148.0,Success Stories,"9780060927196 In Sucess Stories, an exceptiona..."
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,The Rainbow People,"9780064404419 ""Culled from 69 stories collecte..."
412,9780064405713,0064405710,Crazy Lady!,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=aJwh7...,Increasingly alienated from his widowed father...,1995.0,3.64,192.0,1481.0,Crazy Lady!,9780064405713 Increasingly alienated from his ...
731,9780141015088,014101508X,How to Breathe Underwater,Julie Orringer,Families,http://books.google.com/books/content?id=t1v9V...,In her dazzling first book Julie Orringer dive...,2005.0,3.96,222.0,188.0,How to Breathe Underwater: Stories,9780141015088 In her dazzling first book Julie...
775,9780141310688,0141310685,Westmark,Lloyd Alexander,Juvenile Fiction,http://books.google.com/books/content?id=v5U-P...,"Theo, a boy fleeing from criminal charges, fal...",2002.0,3.92,184.0,4049.0,Westmark,"9780141310688 Theo, a boy fleeing from crimina..."
872,9780143039853,0143039857,The Outsiders,S. E. Hinton;Jodi Picoult,Fiction,http://books.google.com/books/content?id=9PyIP...,The struggle of three brothers to stay togethe...,1967.0,4.08,160.0,1558.0,The Outsiders,9780143039853 The struggle of three brothers t...
910,9780156030489,0156030489,Kiffe Kiffe Tomorrow,Faïza Guène;Sarah Adams,Fiction,http://books.google.com/books/content?id=fv8tv...,"Struggling with an overworked mother, an absen...",2006.0,3.38,179.0,1026.0,Kiffe Kiffe Tomorrow,9780156030489 Struggling with an overworked mo...
1197,9780312263232,0312263236,Four Mothers,Shifra Horn;Dalya Bilu,Fiction,http://books.google.com/books/content?id=md0QD...,This beautifully imagined debut novel tells th...,2000.0,3.69,276.0,198.0,Four Mothers: A Novel,9780312263232 This beautifully imagined debut ...
1220,9780312315733,0312315732,Little Children,Tom Perrotta,Fiction,http://books.google.com/books/content?id=j73yQ...,"A group of young suburban parents, including a...",2004.0,3.62,355.0,25811.0,Little Children: A Novel,9780312315733 A group of young suburban parent...
1250,9780312421991,0312421990,What Was She Thinking?,Zoë Heller,Fiction,http://books.google.com/books/content?id=TWviK...,When her best friend Sheba Hart's love affair ...,2004.0,3.71,258.0,13150.0,What Was She Thinking?: Notes on a Scandal: A ...,9780312421991 When her best friend Sheba Hart'...
1386,9780330340199,0330340190,In Pharaoh's Army,Tobias Wolff,"Authors, American",http://books.google.com/books/content?id=TO77D...,Having survived the extraordinary childhood re...,1995.0,4.08,224.0,21.0,In Pharaoh's Army: Memories of a Lost War,9780330340199 Having survived the extraordinar...
1588,9780349113005,0349113009,Embrace,Mark Behr,Fiction,http://books.google.com/books/content?id=yRpVH...,EMBRACE is the story of the awakening of Karl ...,2001.0,3.75,726.0,70.0,Embrace,9780349113005 EMBRACE is the story of the awak...
1638,9780374299194,0374299196,The Discomfort Zone,Jonathan Franzen,Biography & Autobiography,http://books.google.com/books/content?id=Z2vOA...,The author describes growing up in a family of...,2006.0,3.39,195.0,4660.0,The Discomfort Zone: A Personal History,9780374299194 The author describes growing up ...
1652,9780374528539,0374528535,"Get Out of My Life, But First Could You Drive ...",Anthony E. Wolf,Family & Relationships,http://books.google.com/books/content?id=oKdbC...,A lighthearted but insightful guide to raising...,2002.0,3.94,240.0,1301.0,"Get Out of My Life, But First Could You Drive ...",9780374528539 A lighthearted but insightful gu...
1799,9780385264730,0385264739,Children of the Alley,Najīb Maḥfūẓ,Fiction,http://books.google.com/books/content?id=1XmQt...,The story of an Egyptian family mirrors the sp...,1996.0,4.10,464.0,1124.0,Children of the Alley,9780385264730 The story of an Egyptian family ...
1844,9780385481960,0385481969,Youth in Revolt,C. D. Payne,Fiction,http://books.google.com/books/content?id=cZKdO...,"Nick Twisp, a dark and precocious fourteen-yea...",1996.0,4.02,512.0,8158.0,Youth in Revolt: The Journals of Nick Twisp,"9780385481960 Nick Twisp, a dark and precociou..."
1880,9780385732550,0385732554,The Giver,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=oZRlY...,"At the age of twelve, Jonas, a young boy from ...",2006.0,4.12,208.0,1464909.0,The Giver,"9780385732550 At the age of twelve, Jonas, a y..."
1888,9780393040586,0393040585,The Confident Child,T. E. Apter,Family & Relationships,http://books.google.com/books/content?id=stxpQ...,"Focusing on children from age five to fifteen,...",1997.0,3.62,270.0,13.0,"The Confident Child: Raising a Child to Try, L...",9780393040586 Focusing on children from age fi...
1939,9780393926118,0393926117,The Norton Anthology of Short Fiction,Ronald Verlin Cassill;Richard Bausch,Fiction,http://books.google.com/books/content?id=P-v9G...,The classroom standard for readers and aspirin...,2006.0,4.17,1776.0,645.0,The Norton Anthology of Short Fiction,9780393926118 The classroom standard for reade...
2218,9780440506812,0440506816,Your Eight Year Old,Louise Bates Ames;Carol Chase Haber,Family & Relationships,NaN,"The eight-year-old child is an exuberant, outg...",1990.0,3.88,160.0,177.0,Your Eight Year Old: Lively and Outgoing,9780440506812 The eight-year-old child is an e...
2257,9780446362665,0446362662,Summer of Night,Dan Simmons,Fiction,http://books.google.com/books/content?id=AVfhS...,"In the summer of 1960 in Elm Haven, Illinois, ...",1992.0,4.02,600.0,15327.0,Summer of Night,9780446362665 In the summer of 1960 in Elm Hav...
2664,9780553212167,0553212168,The Brothers Karamazov,Fyodor Dostoyevsky,Fiction,http://books.google.com/books/content?id=ZI2nc...,The violent lives of three sons are exposed wh...,1970.0,4.32,1072.0,972.0,The Brothers Karamazov,9780553212167 The violent lives of three sons ...
2805,9780571084838,0571084834,Lord of the Flies,William Golding,Airplane crash survival,NaN,After a plane crash strands them on a tropical...,1954.0,3.67,223.0,4498.0,Lord of the Flies,9780571084838 After a plane crash strands them...
2961,9780670886586,0670886580,Haroun and the Sea of Stories,Salman Rushdie,Fiction,http://books.google.com/books/content?id=O-6nP...,It all begins with a letter. Fall in love with...,1999.0,4.01,224.0,21536.0,Haroun and the Sea of Stories,9780670886586 It all begins with a letter. Fal...
3317,9780743243780,0743243781,Teacher Man,Frank McCourt,Biography & Autobiography,http://books.google.com/books/content?id=Yhgcw...,The author describes his coming of age as a te...,2006.0,3.75,272.0,25726.0,Teacher Man: A Memoir,9780743243780 The author describes his coming ...
3353,9780743272773,0743272773,How to Win Friends and Influence People for Te...,Donna Dale Carnegie,Self-Help,http://books.google.com/books/content?id=eIc2l...,"Donna Dale Carnegie, daughter of the late moti...",2005.0,3.90,208.0,426.0,How to Win Friends and Influence People for Te...,"9780743272773 Donna Dale Carnegie, daughter of..."
3390,9780743454537,0743454537,My Sister's Keeper,Jodi Picoult,Fiction,http://books.google.com/books/content?id=vGZSs...,A popular novel about a girl suing her parents...,2005.0,4.07,423.0,950402.0,My Sister's Keeper: A Novel,9780743454537 A popular novel about a girl sui...
3421,9780743487566,0743487567,The Scarlet Letter,Nathaniel Hawthorne;Margaret Brantley,Fiction,http://books.google.com/books/content?id=y5qkB...,ENDURING LITERATURE ILLUMINATED BY PRACTICAL S...,2004.0,3.39,400.0,1361.0,The Scarlet Letter,9780743487566 ENDURING LITERATURE ILLUMINATED ...
3451,9780747238904,0747238901,The Brotherhood of the Rose,David Morrell,NaN,http://books.google.com/books/content?id=bwNnP...,Chris and Saul were orphans - raised in a Phil...,1992.0,4.13,416.0,5299.0,The Brotherhood of the Rose,9780747238904 Chris and Saul were orphans - ra...
3478,9780747574651,0747574650,Old School,Tobias Wolff,Authors,http://books.google.com/books/content?id=qNrFw...,"It's 1960, in America, at a prestigious boys' ...",2005.0,3.82,195.0,7763.0,Old School,"9780747574651 It's 1960, in America, at a pres..."
3582,9780763621643,0763621641,Castle Diary,Richard Platt;Chris Riddell,Juvenile Fiction,http://books.google.com/books/content?id=rFUBA...,As a page in his uncle's castle in thirteenth-...,2003.0,3.84,128.0,1072.0,Castle Diary: The Journal of Tobias Burgess,9780763621643 As a page in his uncle's castle ...
3667,9780765357663,0765357666,Hidden Talents,David Lubar,Juvenile Fiction,http://books.google.com/books/content?id=wgEFP...,When thirteen-year-old Martin Anderson arrives...,2007.0,3.93,240.0,2333.0,Hidden Talents,9780765357663 When thirteen-year-old Martin An...
3719,9780785260059,0785260056,The Power of One,John C. Maxwell;Thomas G. Addington,Business & Economics,http://books.google.com/books/content?id=L_FGs...,In this 30-day companion workbook to There's N...,2004.0,4.28,256.0,16.0,"The Power of One: One Person, One Rule, One Month",9780785260059 In this 30-day companion workboo...
4193,9780880015080,088001508X,First Love,Joyce Carol Oates,Fiction,http://books.google.com/books/content?id=Wp2vI...,A thirteen-year-old girl moves with her mother...,1997.0,3.19,86.0,557.0,First Love,9780880015080 A thirteen-year-old girl moves w...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...
4272,9780965020596,0965020592,Fahrenheit 451,Ray Bradbury,Book burning,NaN,A bookburner official in a future fascist stat...,2001.0,3.98,190.0,185.0,Fahrenheit 451,9780965020596 A bookburner official in a futur...
4294,9780974607894,0974607894,First Love,Ivan Sergeevich Turgenev,Fiction,http://books.google.com/books/content?id=VcNvD...,"This vivid, sensitive tale of adolescent love ...",2004.0,3.79,124.0,5551.0,First Love,"9780974607894 This vivid, sensitive tale of ad..."
4327,9781400033546,1400033543,You Shall Know Our Velocity!,Dave Eggers,Fiction,http://books.google.com/books/content?id=ucF8n...,"After acquiring $32,000, Will and Hand, devast...",2003.0,3.63,401.0,25360.0,You Shall Know Our Velocity!,"9781400033546 After acquiring $32,000, Will an..."
4371,9781400065011,1400065011,There's a (slight) Chance I Might be Going to ...,Laurie Notaro,Cities and towns,http://books.google.com/books/content?id=Or9pk...,"The first novel from the ""New York Times"" best...",2007.0,3.55,320.0,36.0,There's a (slight) Chance I Might be Going to ...,"9781400065011 The first novel from the ""New Yo..."
4421,9781401211349,1401211348,How to Talk So Teens Will Listen & Listen So T...,Adele Faber,Communication in families,NaN,Presents a practical guide that addresses many...,2006.0,4.11,187.0,1522.0,How to Talk So Teens Will Listen & Listen So T...,9781401211349 Presents a practical guide that ...
4607,9781561796779,1561796778,"Boomers, Xers, and Other Strangers",Rick Hicks;Kathy Hicks,Social Science,http://books.google.com/books/content?id=IogMA...,The authors maintain that children's core valu...,1999.0,3.36,384.0,28.0,"Boomers, Xers, and Other Strangers: Understand...",9781561796779 The authors maintain that childr...
4713,9781576839546,1576839540,Parenting with Love and Logic,Foster Cline;Jim Fay,Family & Relationships,http://books.google.com/books/content?id=TpCtP...,Cline and Fay offer advice to help parents rai...,2006.0,4.07,271.0,9486.0,Parenting with Love and Logic: Teaching Childr...,9781576839546 Cline and Fay offer advice to he...
4770,9781582433226,1582433224,A Complicated Kindness,Miriam Toews,Fiction,http://books.google.com/books/content?id=Vy6Ct...,"A witty, beleaguered teenager whose family is ...",2005.0,3.65,253.0,17112.0,A Complicated Kindness,"9781582433226 A witty, beleaguered teenager wh..."
4808,9781586853334,1586853333,The Big Book of Boy Stuff,Bart King,Juvenile Nonfiction,http://books.google.com/books/content?id=08Ilm...,There's this boy. Let's say he's somewhere bet...,2004.0,4.24,292.0,141.0,The Big Book of Boy Stuff,9781586853334 There's this boy. Let's say he's...
4825,9781589971288,1589971280,Creative Correction,Lisa Whelchel,Family & Relationships,http://books.google.com/books/content?id=haewm...,In addition to advice on topics such as siblin...,2005.0,3.93,367.0,1071.0,Creative Correction: Extraordinary Ideas for E...,9781589971288 In addition to advice on topics ...
4906,9781594481772,1594481776,The Kite Runner,Khaled Hosseini,Fiction,http://books.google.com/books/content?id=3GqcP...,Traces the unlikely friendship of a wealthy Af...,2005.0,4.28,383.0,5241.0,The Kite Runner,9781594481772 Traces the unlikely friendship o...
5100,9781889032207,1889032204,Teach Them Diligently,Louis Paul Priolo,Religion,http://books.google.com/books/content?id=VHL3A...,The bookshelves in your home no doubt contain ...,2000.0,4.24,162.0,294.0,Teach Them Diligently: How to Use the Scriptur...,9781889032207 The bookshelves in your home no ...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...